
title: QA Site for Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

repo_name: "This-should-be-overridden-by-github-actions-script"

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "This-should-be-overridden-by-github-actions-script"
repo: ucsb-cs156-s23/team02-s23-7pm-3
owner: ucsb-cs156-s23
repo_name: team02-s23-7pm-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjQ5OTAyNTkx","is_bot":false,"login":"KaneD985","name":"Kane Deng"},"headRefName":"Kane-AmusementParksIssues","number":16,"title":"Added issues for AmusementParks","url":"https://github.com/ucsb-cs156-s23/team02-s23-7pm-3/pull/16"},{"author":{"id":"MDQ6VXNlcjg2NzQ4NzMx","is_bot":false,"login":"nagpalishaan","name":""},"headRefName":"Ishaan-IceCreamShopIssues","number":15,"title":"Added Issues for Ice Cream Shops","url":"https://github.com/ucsb-cs156-s23/team02-s23-7pm-3/pull/15"},{"author":{"id":"U_kgDOBXRUhw","is_bot":false,"login":"nickzahlis","name":""},"headRefName":"Nick-SchoolIssues","number":14,"title":"Added Issues for Schools","url":"https://github.com/ucsb-cs156-s23/team02-s23-7pm-3/pull/14"},{"author":{"id":"MDQ6VXNlcjc3NDA1OTEx","is_bot":false,"login":"wq12li","name":""},"headRefName":"Yiu-Shing-VideoGamesIssues","number":13,"title":"Create 5 issues for new game table","url":"https://github.com/ucsb-cs156-s23/team02-s23-7pm-3/pull/13"},{"author":{"id":"MDQ6VXNlcjU5NzkwNjQ0","is_bot":false,"login":"zihaoxu20010109","name":"Hardy Xu"},"headRefName":"Hardy-BookIssues","number":12,"title":"hx -adding booksissues","url":"https://github.com/ucsb-cs156-s23/team02-s23-7pm-3/pull/12"}]
