
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/team02-s23-7pm-3
owner: ucsb-cs156-s23
repo_name: team02-s23-7pm-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjc3NDA1OTEx","is_bot":false,"login":"wq12li","name":""},"headRefName":"Yiu-Shing-GETPOST","number":55,"title":"Add GamesController, its test, and \"GET all\" and POST","url":"https://github.com/ucsb-cs156-s23/team02-s23-7pm-3/pull/55"},{"author":{"id":"U_kgDOBXRUhw","is_bot":false,"login":"nickzahlis","name":""},"headRefName":"Nick-SchoolDatabaseTable","number":54,"title":"Add database table for schools","url":"https://github.com/ucsb-cs156-s23/team02-s23-7pm-3/pull/54"},{"author":{"id":"MDQ6VXNlcjc3NDA1OTEx","is_bot":false,"login":"wq12li","name":""},"headRefName":"Yiu-Shing-GamesDatabase","number":51,"title":"Create database for Games","url":"https://github.com/ucsb-cs156-s23/team02-s23-7pm-3/pull/51"}]
